object Vers {
    const val material = "1.6.1"
    const val androidx = "1.8.0"
    const val appcompat = "1.4.2"
    const val constraintlayout = "2.1.4"
    const val fragment = "1.5.0"
    const val lifecycle = "2.5.0"
    const val datastore = "1.0.0"
    const val recyclerview = "1.2.1"
    const val viewpager2 = "1.0.0"
    const val navigation = "2.5.0"
    const val hilt = "2.42"
    const val room = "2.3.0"
    const val work = "2.7.1"
    const val gson = "2.9.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.10.0"
    const val rxjava = "3.0.0"
    const val glide = "4.13.2"
    const val arouter = "1.5.2"
    const val coroutines = "1.6.1"
    const val kotlin = "1.7.10"
    const val junit = "4.13.2"
    const val testExtJunit = "1.1.3"
    const val textExpresso = "3.4.0"
}