package pro.ply.ui.widget

object Text {
    const val s = "fdfdfdfdfdfdfddfdfdfdfsfdsfdsfdfsfsdfsfdsfsfsfdsfdsfsdfdsfsfdsfsfsfsdfsfsfsfsfsdfsfsdfsdfsfsfsdfsfdsfdsfdsfsfdsfsfdsfdsdfsdfsfdsfdsfsdfsddfsfdsdfdsfsdfsdfsfsdfsdfsfdsfsdfsfd"
}